package scouter

var (
	mobNames = map[string]map[string]uint{
		"EW": {
			"Yilan":            184,
			"Sugriva":          185,
			"Aegeiros":         195,
			"Minerva":          194,
			"Storsie":          175,
			"Hulder":           174,
			"Gurangatch":       215,
			"Petalodus":        214,
			"Fan Ail":          225,
			"Arch-Eta":         224,
			"Mousse Princess":  204,
			"Lunatender Queen": 205,
		},
		"DT": {
			"Nechuciho":         235,
			"Queen Hawk":        234,
			"The Raintriller":   244,
			"Pkuucha":           245,
			"Starcrier":         255,
			"Rrax Yity'a":       254,
			"Yehehetoaua'pyo":   264,
			"Keheniheyamewi":    265,
			"Urna Variabilis":   275,
			"Heshuala":          274,
			"Cat's Eye":         285,
			"Sally the Sweeper": 284,
		},
		"SB": {
			"Funa Yurei":  84,
			"Oni Yumemi":  85,
			"Gajasura":    89,
			"Angada":      90,
			"Orcus":       99,
			"Erle":        100,
			"Vochstein":   104,
			"Aqrabuamelu": 105,
			"Mahisha":     109,
			"Luminare":    110,
			"Girimekhala": 94,
			"Sum":         95,
		},
		"SHB": {
			"Nariphon":          115,
			"O Poorest Pauldia": 130,
			"Grassman":          135,
			"Nuckelavee":        114,
			"Huracan":           120,
			"Li'l Murderer":     119,
			"Sugaar":            125,
			"Maliktender":       124,
			"Supay":             134,
			"Baal":              140,
			"Rusalka":           139,
			"The Mudman":        129,
		},
	}
)
